create database shop DEFAULT CHARACTER SET utf8;

USE mysql;
-- 为root用户赋予外网访问的权限
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '909090' WITH GRANT OPTION;
FLUSH PRIVILEGES;

SET PASSWORD FOR 'root'@'localhost' = PASSWORD('909090');
FLUSH PRIVILEGES;

